### ISSUE TITLE
Circle Shapes turning into Squares

### ISSUE THREAD

**Issue by aritracci** [DarkDefender/superpix#1]
The port converts circular shapes into squares. Did you ever test svg images such as a circle and compare the results? If the error occurs for you, any idea what could be the issue?

**Comment by DarkDefender** [comment]
I didn't port that functionality because I didn't need it at the time.

So the current code only support strokes (lines).
If you port that functionality too, I will gladly merge it in here!

**Comment by aritracci** [comment]
Any tips /guidance on how i should approach porting that functionality? I am trying to look through the bitbucket but not sure where the curves are being pixelated.

**Comment by aritracci** [comment]
Also if you don't mind, is there any way I can contact you through email? I have just a few questions if you have the time.

**Comment by DarkDefender** [comment]
IIRC, there should be different code paths. IE one for paths (lines that I ported), one for circles, one for rectangles etc.

You don't have to write an email with the extra questions. You can just ask them here. Nobody else has filed a ticked to this repo in a long time. So we can just use this to chat :P

**Comment by aritracci** [comment]
Is it possible to commission you to finish circular paths and Antialiaser?

**Comment by DarkDefender** [comment]
You will have to clarify a bit:

Circular paths == Ovals/Circles (?)
Antialiaser == ???

I might have some time next week to take a look at it.

**Comment by aritracci** [comment]
Circular paths such that if given an svg file, the pixelated image would come out with curved pixelated lines. As for the antialiaser,  it is included in the original bitbucket source code. It adds extra pixels to smooth out sharp lines. Is it possible for you to complete at-least circular paths or antialiaser within the next 16 hours?

**Comment by DarkDefender** [comment]
That should already be implemented. 
I've tried to some simple example drawings with inkscape and it seems to work fine for me.
Could you give me an example file?

**Comment by aritracci** [comment]
https://www.flaticon.com/free-icon/share_128005#term=curve&page=1&position=2 try converting this.

**Comment by DarkDefender** [comment]
Right, you need to convert the paths to something that consists of strait lines. The programs currently doesn't do this for you (because I didn't need it at the time I wrote it).

Or just add enough points to the curve so it is not noticeable. I don't have time to fix this in such short time span

**Comment by DarkDefender** [comment]
Or to be more precise, I have some code that should handle bezier curves. (If poly_path is set to false). But it is not working right now. Only polygon paths working

**Comment by aritracci** [comment]
Hey again, I was wondering if you could do me a favor. I am trying to use this project as my final project to graduate this week. Would you mind letting me use this work? If so would, do you mind making this repo private till may 24th? I would greatly appreciate if you could this for me.  I am struggling with my graphics class heavily and your port is my only solution. Thank you in advance!

**Comment by aritracci** [comment]
I am willing to compensate for this if it is required. Looking to hear from you as soon as possible! Thank you again.

**Comment by DarkDefender** [comment]
I've hunted down the bugs in my code and it should now create the same lines as original java code.

I am sadly no willing to help you cheat. But I hope that my code is useful nonetheless.
